"""add task triggered_rerun field

Revision ID: 2dcebfab5acb
Revises: 5fd7fe1e2a08
Create Date: 2025-04-11 01:56:13.139969

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dcebfab5acb"
down_revision: str | None = "5fd7fe1e2a08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("triggered_rerun", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "triggered_rerun")
    # ### end Alembic commands ###
