"""add max attempts

Revision ID: 5a36aa9e3ca6
Revises: a2b6c9ebc326
Create Date: 2025-03-08 20:38:57.379709

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a36aa9e3ca6"
down_revision: str | None = "a2b6c9ebc326"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("max_attempts", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "max_attempts")
    # ### end Alembic commands ###
