"""add_marked_for_submission_field

Revision ID: 5fd7fe1e2a08
Revises: ece55a890e78
Create Date: 2025-04-09 15:14:30.762197

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fd7fe1e2a08"
down_revision: str | None = "ece55a890e78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_attempt",
        sa.Column("marked_for_submission", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_attempt", "marked_for_submission")
    # ### end Alembic commands ###
